- IP-CIDR,140.112.161.116/32,DIRECT
- IP-CIDR,61.221.215.25/32,DIRECT
- IP-CIDR,209.141.58.162/32,DIRECT
- DOMAIN,ocw.aca.ntu.edu,DIRECT
- DOMAIN-SUFFIX,windows.com,DIRECT
- DOMAIN-SUFFIX,microsoftonline.com,DIRECT
- DOMAIN-SUFFIX,microsoft.com,DIRECT
- DOMAIN-SUFFIX,bing.com,DIRECT
- DOMAIN-SUFFIX,bingapis.com,DIRECT
- DOMAIN-SUFFIX,cambridge.org,DIRECT
- DOMAIN-SUFFIX,duolingo.com,DIRECT
- DOMAIN-SUFFIX,msidentity.com,DIRECT
- DOMAIN-SUFFIX,router.home,DIRECT
- DOMAIN,epg.112114.eu.org,DIRECT
- DOMAIN-SUFFIX,italki.com,DIRECT
- DOMAIN-SUFFIX,pool.ntp.org,DIRECT
- DOMAIN-SUFFIX,cloudfront.net,DIRECT
- DOMAIN-SUFFIX,apple.com,DIRECT
- DOMAIN-SUFFIX,visualstudio.com,DIRECT
- DOMAIN-SUFFIX,revma.com,DIRECT
- DOMAIN-SUFFIX,rastream.com,DIRECT
- DOMAIN,proxy-kr.radioline.fr,DIRECT
- DOMAIN,edge.microsoft.com,DIRECT
- DOMAIN,cdn3.132.us.kg,DIRECT
- DOMAIN-SUFFIX,163189.xyz,DIRECT
- DOMAIN-SUFFIX,vip-tptv.xyz,DIRECT
- DOMAIN-SUFFIX,iptv200.com,DIRECT
- DOMAIN-SUFFIX,zaobao.com,DIRECT
- DOMAIN-SUFFIX,chinatimes.com,DIRECT
- DOMAIN,vscode-sync.trafficmanager.net,DIRECT
- DOMAIN-SUFFIX,waqi.info,DIRECT
- DOMAIN,mgtv.ottiptv.cc,DIRECT
- DOMAIN,englishnewsinlevels.com,DIRECT
- DOMAIN,globalnews.ca,DIRECT
- DOMAIN-SUFFIX,epg-1.iill.top, Video-Group
- DOMAIN-SUFFIX,epg.iill.top, Video-Group
- DOMAIN,live.ottiptv.cc, Auto-Select
# 从 nav.xml 自动添加的直连站点
- DOMAIN-SUFFIX,80sgod.com,DIRECT
- DOMAIN-SUFFIX,abskoop.com,DIRECT
- DOMAIN-SUFFIX,aqicn.org,DIRECT
- DOMAIN-SUFFIX,bloomberg.com,DIRECT
- DOMAIN,chinadaily.com.cn,DIRECT
- DOMAIN-SUFFIX,chinadigitaltimes.net,DIRECT
- DOMAIN,cnbeta.com.tw,DIRECT
- DOMAIN-SUFFIX,dictionary.com,DIRECT
- DOMAIN-SUFFIX,dida365.com,DIRECT
- DOMAIN,dormousehole.readthedocs.org,DIRECT
- DOMAIN-SUFFIX,fast8.com,DIRECT
- DOMAIN-SUFFIX,ip125.com,DIRECT
- DOMAIN-SUFFIX,jiumodiary.com,DIRECT
- DOMAIN-SUFFIX,krea.ai,DIRECT
- DOMAIN-SUFFIX,kylc.com,DIRECT
- DOMAIN-SUFFIX,mysmartadvisor.com,DIRECT
- DOMAIN-SUFFIX,neikuw.com,DIRECT
- DOMAIN-SUFFIX,overapi.com,DIRECT
- DOMAIN-SUFFIX,oxfordlearnersdictionaries.com,DIRECT
- DOMAIN-SUFFIX,pchome.net,DIRECT
- DOMAIN-SUFFIX,pcpop.com,DIRECT
- DOMAIN-SUFFIX,picsart.com,DIRECT
- DOMAIN-SUFFIX,quodb.com,DIRECT
- DOMAIN-SUFFIX,raphael.app,DIRECT
- DOMAIN,redis.readthedocs.org,DIRECT
- DOMAIN-SUFFIX,regexlib.com,DIRECT
- DOMAIN-SUFFIX,scmp.com,DIRECT
- DOMAIN-SUFFIX,shudu.one,DIRECT
- DOMAIN-SUFFIX,simplywall.st,DIRECT
- DOMAIN-SUFFIX,sspai.com,DIRECT
- DOMAIN-SUFFIX,thefreedictionary.com,DIRECT
- DOMAIN-SUFFIX,tjxz.cc,DIRECT
- DOMAIN-SUFFIX,tutorialspoint.com,DIRECT
- DOMAIN-SUFFIX,v2ex.com,DIRECT
- DOMAIN-SUFFIX,voicetube.com,DIRECT
- DOMAIN-SUFFIX,worldgovernmentbonds.com,DIRECT
- DOMAIN-SUFFIX,xiaolipan.com,DIRECT
- DOMAIN,zol.com.cn,DIRECT
