- IP-CIDR,140.112.161.116/32,DIRECT
- IP-CIDR,61.221.215.25/32,DIRECT
- IP-CIDR,209.141.58.162/32,DIRECT
- DOMAIN,ocw.aca.ntu.edu,DIRECT
- DOMAIN-SUFFIX,windows.com,DIRECT
- DOMAIN-SUFFIX,microsoftonline.com,DIRECT
- DOMAIN-SUFFIX,microsoft.com,DIRECT
- DOMAIN-SUFFIX,bing.com,DIRECT
- DOMAIN-SUFFIX,bingapis.com,DIRECT
- DOMAIN-SUFFIX,cambridge.org,DIRECT
- DOMAIN-SUFFIX,duolingo.com,DIRECT
- DOMAIN-SUFFIX,msidentity.com,DIRECT
- DOMAIN-SUFFIX,router.home,DIRECT
- DOMAIN,epg.112114.eu.org,DIRECT
- DOMAIN-SUFFIX,italki.com,DIRECT
- DOMAIN-SUFFIX,pool.ntp.org,DIRECT
- DOMAIN-SUFFIX,cloudfront.net,DIRECT
- DOMAIN-SUFFIX,apple.com,DIRECT
- DOMAIN-SUFFIX,visualstudio.com,DIRECT
- DOMAIN-SUFFIX,revma.com,DIRECT
- DOMAIN-SUFFIX,rastream.com,DIRECT
- DOMAIN,proxy-kr.radioline.fr,DIRECT
- DOMAIN,edge.microsoft.com,DIRECT
- DOMAIN,cdn3.132.us.kg,DIRECT
- DOMAIN-SUFFIX,163189.xyz,DIRECT
- DOMAIN-SUFFIX,vip-tptv.xyz,DIRECT
- DOMAIN-SUFFIX,iptv200.com,DIRECT